/* tslint:disable */
/* eslint-disable */
/**
 * api_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegionSummary
 */
export interface RegionSummary {
    /**
     * 
     * @type {Array<string>}
     * @memberof RegionSummary
     */
    sentences: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof RegionSummary
     */
    start: number;
    /**
     * 
     * @type {number}
     * @memberof RegionSummary
     */
    end: number;
}

/**
 * Check if a given object implements the RegionSummary interface.
 */
export function instanceOfRegionSummary(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sentences" in value;
    isInstance = isInstance && "start" in value;
    isInstance = isInstance && "end" in value;

    return isInstance;
}

export function RegionSummaryFromJSON(json: any): RegionSummary {
    return RegionSummaryFromJSONTyped(json, false);
}

export function RegionSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegionSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sentences': json['sentences'],
        'start': json['start'],
        'end': json['end'],
    };
}

export function RegionSummaryToJSON(value?: RegionSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sentences': value.sentences,
        'start': value.start,
        'end': value.end,
    };
}

